/*  La durata di un'asta non può essere inferiore a tre giorni. 
    In un mese un oggetto non può essere messo all'asta più di tre volte. 
    Il rilancio minimo dev'essere almeno il 10% del prezzo base. 
    Eccezioni: 
        rilancio_minimo_troppo_basso, asta_troppo_breve, oggetto_troppe_volte_in_vendita. 
*/

CREATE OR REPLACE TRIGGER AST BEFORE INSERT ON ASTA
FOR EACH ROW
DECLARE

CONT_VOLTE          NUMBER(2,0);
TOO_SHORT_DURATION  EXCEPTION;
TOO_MANY_TIMES      EXCEPTION;
TOO_LOW             EXCEPTION;

BEGIN

IF TO_DATE(:NEW.DATA_INIZIO, 'YYYY-DD-MM') - TO_DATE(:NEW.DATA_FINE, 'YYYY-DD-MM') < 3 THEN
	RAISE TOO_SHORT_DURATION;
END IF;

SELECT COUNT(*) INTO CONT_VOLTE
FROM ASTA
WHERE CODICE_OGGETTO=:NEW.CODICE_OGGETTO AND TO_DATE(DATA_INIZIO, 'MM')=TO_DATE(:NEW.DATA_INIZIO, 'MM');

IF CONT_VOLTE>3 THEN
	RAISE TOO_MANY_TIMES;
END IF;

IF :NEW.RILANCIO_MIN < 0.10*:NEW.PREZZO_BASE THEN
	RAISE TOO_LOW;
END IF;

EXCEPTION
    WHEN TOO_SHORT_DURATION THEN
        RAISE_APPLICATION_ERROR(-20003, 'TROPPE VOLTE');

    WHEN TOO_MANY_TIMES THEN
        RAISE_APPLICATION_ERROR(-20002, 'TROPPE VOLTE');

    WHEN TOO_LOW THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERRORE');
END;